server:
  port: 8081

file:
  storage:
    location: fileStorage

spring:
  servlet:
    multipart:
      enabled: true
      location: temp123
      file-size-threshold: 5MB
      max-file-size: 1MB
      max-request-size: 20MB

  datasource:
    url: jdbc:sqlserver://DESKTOP-A2AIBH6\SRVDBP01;
    username: sa
    password: 1234567
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver